CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    topic VARCHAR(50) NOT NULL,
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);