spring.application.name=productcataloglab
application-description=Aplikacja do zarzadzania katalogiem produktow
application-version=1.0.0

db.ip=${SPRING_DATASOURCE_IP:db-service}
db.port=${SPRING_DATASOURCE_PORT:5432}
db.name=${SPRING_DATASOURCE_DB:productcataloglab}
db.username=${SPRING_DATASOURCE_USERNAME:postgres}
db.password=${SPRING_DATASOURCE_PASSWORD:123}
db.driver=org.postgresql.Driver
db.protocol=jdbc:postgresql

spring.datasource.url=${db.protocol}://${db.ip}:${db.port}/${db.name}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=${db.driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html
